{% set name = "netpbmfile" %}
{% set version = "2023.8.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netpbmfile-{{ version }}.tar.gz
  sha256: 3bf1137b53bbcdb77ebec77369d338e1ad0a9d2b90f22fa418bba18eb5f380b9

build:
  number: 0
  noarch: python
  entry_points:
    - netpbmfile = netpbmfile.netpbmfile:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - numpy
    - matplotlib-base
    - python >=3.9
    - tifffile

test:
  imports:
    - netpbmfile
  commands:
    - pip list
    - pip check
    - netpbmfile --doctest
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read and write Netpbm files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/netpbmfile/

extra:
  recipe-maintainers:
    - cgohlke
    - goanpeca
