{% set name = "netpbmfile" %}
{% set version = "2026.1.8" %}
{% set sha256 = "b9098ad645f31e1b58603c61132cbb84fa3d50c7a25f1cf10fc96897818b28c3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - netpbmfile = netpbmfile.netpbmfile:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - netpbmfile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com/
  summary: Read and write Netpbm files
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Netpbmfile is a Python library to read and write image files in the Netpbm or related formats.
  dev_url: https://github.com/cgohlke/netpbmfile/

extra:
  recipe-maintainers:
    - cgohlke
    - goanpeca
